#!/usr/bin/env python3
"""
run_all_prompts.py — Async Batch Execution of All 38 Research Prompts

Reads scripts/prompts/config.json and sends all prompts to the Perplexity API
concurrently using AsyncPerplexity, with rate-limiting via asyncio.Semaphore.

Usage:
    python scripts/run_all_prompts.py                        # run all 38
    python scripts/run_all_prompts.py --concurrency 5        # limit to 5 concurrent
    python scripts/run_all_prompts.py --model sonar-pro      # specify model
    python scripts/run_all_prompts.py --dry-run               # preview without API calls
    python scripts/run_all_prompts.py --start 10 --end 20     # run prompts 10-20 only

NOTE: PERPLEXITY_API_KEY must be set as an environment variable.
      If you just ran `setx`, open a new terminal session first.
"""

import argparse
import asyncio
import io
import json
import os
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path

# Force UTF-8 output on Windows (cp1252 can't handle emoji)
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding="utf-8", errors="replace")

PROJECT_ROOT = Path(__file__).resolve().parent.parent

SYSTEM_MESSAGE = (
    "You are the Autonomous AI Coding Research Engine for the SDLC repository. "
    "Produce a comprehensive overview.md research artifact."
)


@dataclass
class PromptResult:
    prompt_id: int
    title: str
    success: bool = False
    error: str = ""
    response_chars: int = 0
    citation_count: int = 0
    prompt_tokens: int = 0
    completion_tokens: int = 0
    total_tokens: int = 0
    cost: float = 0.0
    elapsed: float = 0.0
    output_path: str = ""


@dataclass
class BatchSummary:
    results: list[PromptResult] = field(default_factory=list)
    total_elapsed: float = 0.0

    @property
    def successes(self) -> list[PromptResult]:
        return [r for r in self.results if r.success]

    @property
    def failures(self) -> list[PromptResult]:
        return [r for r in self.results if not r.success]

    @property
    def total_cost(self) -> float:
        return sum(r.cost for r in self.results)

    @property
    def total_tokens_used(self) -> int:
        return sum(r.total_tokens for r in self.results)


def load_config() -> list[dict]:
    config_path = PROJECT_ROOT / "scripts" / "prompts" / "config.json"
    if not config_path.exists():
        print("❌ config.json not found. Run split_prompts.py first:")
        print("   python scripts/split_prompts.py")
        sys.exit(1)
    return json.loads(config_path.read_text(encoding="utf-8"))


def format_output(text: str, citations: list[str], prompt_config: dict) -> str:
    """Format the API response as a markdown document with citations."""
    lines = [text]
    if citations:
        lines.append("\n\n---\n")
        lines.append("## Citations\n")
        for i, url in enumerate(citations, 1):
            lines.append(f"{i}. {url}")
    lines.append(
        f"\n\n<!-- Generated by Perplexity API (sonar-pro) for prompt "
        f"#{prompt_config['id']}: {prompt_config['title']} -->"
    )
    return "\n".join(lines)


async def run_prompt(
    client,
    semaphore: asyncio.Semaphore,
    prompt_config: dict,
    model: str,
    counter: dict,
    reasoning_effort: str | None = None,
) -> PromptResult:
    """Run a single prompt through the Perplexity API with semaphore-based rate limiting."""
    result = PromptResult(
        prompt_id=prompt_config["id"],
        title=prompt_config["title"],
        output_path=prompt_config["output_path"],
    )

    prompt_path = PROJECT_ROOT / prompt_config["prompt_file"]
    if not prompt_path.exists():
        result.error = f"Prompt file not found: {prompt_path}"
        counter["done"] += 1
        print(f"  ❌ [{counter['done']}/{counter['total']}] #{result.prompt_id} — {result.error}")
        return result

    prompt_text = prompt_path.read_text(encoding="utf-8")

    async with semaphore:
        start_time = time.time()
        try:
            api_kwargs = dict(
                model=model,
                messages=[
                    {"role": "system", "content": SYSTEM_MESSAGE},
                    {"role": "user", "content": prompt_text},
                ],
                search_mode="web",
                search_recency_filter="year",
                max_tokens=16384,
                temperature=0.1,
            )
            if reasoning_effort is not None:
                api_kwargs["reasoning_effort"] = reasoning_effort
            response = await client.chat.completions.create(**api_kwargs)

            result.elapsed = time.time() - start_time
            text = response.choices[0].message.content
            citations = getattr(response, "citations", None) or []

            result.response_chars = len(text)
            result.citation_count = len(citations)
            result.success = True

            # Extract usage info
            if response.usage:
                usage = response.usage
                result.prompt_tokens = getattr(usage, "prompt_tokens", 0) or 0
                result.completion_tokens = getattr(usage, "completion_tokens", 0) or 0
                result.total_tokens = getattr(usage, "total_tokens", 0) or 0

                if hasattr(usage, "cost") and usage.cost and hasattr(usage.cost, "total_cost"):
                    result.cost = usage.cost.total_cost
                else:
                    # Estimate: Input $3/1M, Output $15/1M, Search $5/1K requests
                    result.cost = (
                        result.prompt_tokens * 3 / 1_000_000
                        + result.completion_tokens * 15 / 1_000_000
                        + 5 / 1000
                    )

            # Save output
            output_path = PROJECT_ROOT / prompt_config["output_path"]
            output_path.parent.mkdir(parents=True, exist_ok=True)
            formatted = format_output(text, citations, prompt_config)
            output_path.write_text(formatted, encoding="utf-8")

        except Exception as e:
            result.elapsed = time.time() - start_time
            result.error = str(e)

    counter["done"] += 1
    status = "✅" if result.success else "❌"
    cost_str = f"${result.cost:.4f}" if result.cost else "N/A"
    print(
        f"  {status} [{counter['done']}/{counter['total']}] "
        f"#{result.prompt_id:02d} {result.title[:40]:<40} "
        f"{result.response_chars:>6,} chars  {result.elapsed:>5.1f}s  {cost_str}"
    )

    return result


async def run_batch(
    configs: list[dict],
    concurrency: int,
    model: str,
    reasoning_effort: str | None = None,
) -> BatchSummary:
    """Run all prompts concurrently with rate limiting."""
    from perplexity import AsyncPerplexity

    semaphore = asyncio.Semaphore(concurrency)
    counter = {"done": 0, "total": len(configs)}

    summary = BatchSummary()
    start_time = time.time()

    async with AsyncPerplexity() as client:
        tasks = [
            run_prompt(client, semaphore, cfg, model, counter, reasoning_effort)
            for cfg in configs
        ]
        summary.results = await asyncio.gather(*tasks)

    summary.total_elapsed = time.time() - start_time
    return summary


def print_dry_run(configs: list[dict], model: str, concurrency: int, reasoning_effort: str | None = None) -> None:
    """Show what would be executed without making API calls."""
    print("=" * 70)
    print("🔍 DRY RUN — No API calls will be made")
    print(f"   Model:       {model}")
    print(f"   Concurrency: {concurrency}")
    if reasoning_effort:
        print(f"   Reasoning:   {reasoning_effort}")
    print(f"   Prompts:     {len(configs)}")
    print("=" * 70)
    print()

    total_chars = 0
    for cfg in configs:
        prompt_path = PROJECT_ROOT / cfg["prompt_file"]
        exists = prompt_path.exists()
        chars = len(prompt_path.read_text(encoding="utf-8")) if exists else 0
        total_chars += chars
        status = "✅" if exists else "❌ MISSING"
        print(
            f"  {status} #{cfg['id']:02d} {cfg['title'][:45]:<45} "
            f"{chars:>5,} chars → {cfg['output_path']}"
        )

    print()
    print("─" * 70)
    print(f"  Total prompt text:  {total_chars:,} chars")
    # Rough token estimate: ~4 chars per token
    est_tokens = total_chars // 4
    est_input_cost = est_tokens * 3 / 1_000_000
    est_output_cost = len(configs) * 4000 * 15 / 1_000_000  # ~4K output tokens each
    est_search_cost = len(configs) * 5 / 1000
    est_total = est_input_cost + est_output_cost + est_search_cost
    print(f"  Estimated tokens:   ~{est_tokens:,} input tokens")
    print(f"  Estimated cost:     ~${est_total:.2f}")
    print(f"    Input:   ~${est_input_cost:.2f}")
    print(f"    Output:  ~${est_output_cost:.2f}  (assuming ~4K output tokens each)")
    print(f"    Search:  ~${est_search_cost:.2f}")
    print("─" * 70)


def print_summary(summary: BatchSummary) -> None:
    """Print a final summary of the batch execution."""
    print()
    print("=" * 70)
    print("📊 BATCH EXECUTION SUMMARY")
    print("=" * 70)
    print(f"  Total time:       {summary.total_elapsed:.1f}s ({summary.total_elapsed / 60:.1f} min)")
    print(f"  Successes:        {len(summary.successes)} / {len(summary.results)}")
    print(f"  Failures:         {len(summary.failures)} / {len(summary.results)}")
    print(f"  Total tokens:     {summary.total_tokens_used:,}")
    print(f"  Total cost:       ${summary.total_cost:.4f}")
    print()

    if summary.successes:
        total_chars = sum(r.response_chars for r in summary.successes)
        total_citations = sum(r.citation_count for r in summary.successes)
        avg_time = sum(r.elapsed for r in summary.successes) / len(summary.successes)
        print(f"  Total response:   {total_chars:,} chars across {len(summary.successes)} files")
        print(f"  Total citations:  {total_citations}")
        print(f"  Avg response time: {avg_time:.1f}s")

    if summary.failures:
        print()
        print("  ❌ FAILED PROMPTS:")
        for r in summary.failures:
            print(f"     #{r.prompt_id:02d} {r.title}: {r.error}")

    print("=" * 70)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Run all 38 Perplexity API research prompts concurrently"
    )
    parser.add_argument(
        "--concurrency", type=int, default=10,
        help="Max concurrent API requests (default: 10)",
    )
    parser.add_argument(
        "--model", type=str, default="sonar-pro",
        help="Perplexity model to use (default: sonar-pro)",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Show what would be done without making API calls",
    )
    parser.add_argument(
        "--start", type=int, default=None,
        help="Start from prompt ID (inclusive)",
    )
    parser.add_argument(
        "--end", type=int, default=None,
        help="End at prompt ID (inclusive)",
    )
    parser.add_argument(
        "--reasoning-effort", choices=["minimal", "low", "medium", "high"], default=None,
        help="Reasoning effort level (minimal/low/medium/high). Only used with reasoning models.",
    )
    args = parser.parse_args()

    # ── Check API key (skip for dry-run) ───────────────────────────
    if not args.dry_run:
        api_key = os.environ.get("PERPLEXITY_API_KEY")
        if not api_key:
            print("❌ PERPLEXITY_API_KEY environment variable is not set.")
            print("   If you just ran `setx PERPLEXITY_API_KEY ...`, open a new terminal.")
            sys.exit(1)

    # ── Load and filter config ─────────────────────────────────────
    config = load_config()

    if args.start is not None:
        config = [c for c in config if c["id"] >= args.start]
    if args.end is not None:
        config = [c for c in config if c["id"] <= args.end]

    if not config:
        print("❌ No prompts to run after filtering.")
        sys.exit(1)

    # ── Dry run ────────────────────────────────────────────────────
    if args.dry_run:
        print_dry_run(config, args.model, args.concurrency, args.reasoning_effort)
        return

    # ── Check perplexity package ───────────────────────────────────
    try:
        from perplexity import AsyncPerplexity  # noqa: F401
    except ImportError:
        print("❌ perplexity package not installed. Install it:")
        print("   pip install perplexity-ai")
        sys.exit(1)

    # ── Execute batch ──────────────────────────────────────────────
    print("=" * 70)
    print("🚀 BATCH EXECUTION")
    print(f"   Prompts:     {len(config)} ({config[0]['id']}-{config[-1]['id']})")
    print(f"   Model:       {args.model}")
    print(f"   Concurrency: {args.concurrency}")
    if args.reasoning_effort:
        print(f"   Reasoning:   {args.reasoning_effort}")
    print("=" * 70)
    print()

    summary = asyncio.run(run_batch(config, args.concurrency, args.model, args.reasoning_effort))
    print_summary(summary)


if __name__ == "__main__":
    main()
