#!/usr/bin/env python3
"""
test_single_prompt.py — Single Prompt Cost Tester

Sends a single prompt to the Perplexity API (sonar-pro) and displays
cost breakdown, token counts, response length, and citation count.
Saves the output to the mapped path from config.json.

Usage:
    python scripts/test_single_prompt.py              # runs prompt #1
    python scripts/test_single_prompt.py --prompt-id 5
    python scripts/test_single_prompt.py --prompt-id 5 --model sonar-pro

NOTE: PERPLEXITY_API_KEY must be set as an environment variable.
      If you just ran `setx`, open a new terminal session first.
"""

import argparse
import io
import json
import os
import sys
import time
from pathlib import Path

# Force UTF-8 output on Windows (cp1252 can't handle emoji)
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding="utf-8", errors="replace")

PROJECT_ROOT = Path(__file__).resolve().parent.parent

SYSTEM_MESSAGE = (
    "You are the Autonomous AI Coding Research Engine for the SDLC repository. "
    "Produce a comprehensive overview.md research artifact."
)


def load_config() -> list[dict]:
    config_path = PROJECT_ROOT / "scripts" / "prompts" / "config.json"
    if not config_path.exists():
        print("❌ config.json not found. Run split_prompts.py first:")
        print("   python scripts/split_prompts.py")
        sys.exit(1)
    return json.loads(config_path.read_text(encoding="utf-8"))


def find_prompt_config(config: list[dict], prompt_id: int) -> dict:
    for entry in config:
        if entry["id"] == prompt_id:
            return entry
    print(f"❌ Prompt #{prompt_id} not found in config.json")
    sys.exit(1)


def format_output(text: str, citations: list[str], prompt_config: dict) -> str:
    """Format the API response as a markdown document with citations."""
    lines = [text]
    if citations:
        lines.append("\n\n---\n")
        lines.append("## Citations\n")
        for i, url in enumerate(citations, 1):
            lines.append(f"{i}. {url}")
    lines.append(f"\n\n<!-- Generated by Perplexity API (sonar-pro) for prompt #{prompt_config['id']}: {prompt_config['title']} -->")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Test a single Perplexity API prompt")
    parser.add_argument(
        "--prompt-id", type=int, default=1,
        help="Prompt ID to test (default: 1)",
    )
    parser.add_argument(
        "--model", type=str, default="sonar-pro",
        help="Perplexity model to use (default: sonar-pro)",
    )
    parser.add_argument(
        "--reasoning-effort", choices=["minimal", "low", "medium", "high"], default=None,
        help="Reasoning effort level (minimal/low/medium/high). Only used with reasoning models.",
    )
    args = parser.parse_args()

    # ── Check API key ──────────────────────────────────────────────
    api_key = os.environ.get("PERPLEXITY_API_KEY")
    if not api_key:
        print("❌ PERPLEXITY_API_KEY environment variable is not set.")
        print("   If you just ran `setx PERPLEXITY_API_KEY ...`, open a new terminal.")
        sys.exit(1)

    # ── Load config & prompt ───────────────────────────────────────
    config = load_config()
    prompt_config = find_prompt_config(config, args.prompt_id)

    prompt_path = PROJECT_ROOT / prompt_config["prompt_file"]
    if not prompt_path.exists():
        print(f"❌ Prompt file not found: {prompt_path}")
        print("   Run split_prompts.py first: python scripts/split_prompts.py")
        sys.exit(1)

    prompt_text = prompt_path.read_text(encoding="utf-8")

    print("=" * 70)
    print(f"🧪 SINGLE PROMPT TEST")
    print(f"   Prompt:  #{prompt_config['id']} — {prompt_config['title']}")
    print(f"   Model:   {args.model}")
    if args.reasoning_effort:
        print(f"   Reasoning effort: {args.reasoning_effort}")
    print(f"   Output:  {prompt_config['output_path']}")
    print(f"   Prompt length: {len(prompt_text):,} chars")
    print("=" * 70)

    # ── Import and call Perplexity API ─────────────────────────────
    try:
        from perplexity import Perplexity
    except ImportError:
        print("❌ perplexity package not installed. Install it:")
        print("   pip install perplexity-ai")
        sys.exit(1)

    client = Perplexity()  # reads PERPLEXITY_API_KEY env var

    print("\n⏳ Sending request to Perplexity API...\n")
    start_time = time.time()

    try:
        api_kwargs = dict(
            model=args.model,
            messages=[
                {"role": "system", "content": SYSTEM_MESSAGE},
                {"role": "user", "content": prompt_text},
            ],
            search_mode="web",
            search_recency_filter="year",
            max_tokens=16384,
            temperature=0.1,
        )
        if args.reasoning_effort is not None:
            api_kwargs["reasoning_effort"] = args.reasoning_effort
        response = client.chat.completions.create(**api_kwargs)
    except Exception as e:
        print(f"❌ API call failed: {e}")
        sys.exit(1)

    elapsed = time.time() - start_time

    # ── Extract response data ──────────────────────────────────────
    text = response.choices[0].message.content
    citations = getattr(response, "citations", None) or []

    # ── Cost & usage info ──────────────────────────────────────────
    print("─" * 70)
    print("📊 RESPONSE STATS")
    print("─" * 70)
    print(f"  Response time:    {elapsed:.1f}s")
    print(f"  Response length:  {len(text):,} chars")
    print(f"  Citations:        {len(citations)}")

    if response.usage:
        usage = response.usage
        print(f"  Prompt tokens:    {getattr(usage, 'prompt_tokens', 'N/A')}")
        print(f"  Completion tokens:{getattr(usage, 'completion_tokens', 'N/A')}")
        print(f"  Total tokens:     {getattr(usage, 'total_tokens', 'N/A')}")

        # Cost breakdown (if available)
        if hasattr(usage, "cost") and usage.cost:
            cost = usage.cost
            print(f"\n  💰 COST BREAKDOWN:")
            if hasattr(cost, "input_cost"):
                print(f"     Input cost:    ${cost.input_cost:.4f}")
            if hasattr(cost, "output_cost"):
                print(f"     Output cost:   ${cost.output_cost:.4f}")
            if hasattr(cost, "search_cost"):
                print(f"     Search cost:   ${cost.search_cost:.4f}")
            if hasattr(cost, "total_cost"):
                print(f"     Total cost:    ${cost.total_cost:.4f}")
                estimated_all = cost.total_cost * 38
                print(f"\n  📐 ESTIMATED COST FOR ALL 38 PROMPTS: ${estimated_all:.2f}")
        else:
            # Estimate cost from token counts (sonar-pro pricing as of 2025)
            # Input: $3/1M tokens, Output: $15/1M tokens, Search: $5/request
            prompt_tokens = getattr(usage, "prompt_tokens", 0) or 0
            completion_tokens = getattr(usage, "completion_tokens", 0) or 0
            est_input = prompt_tokens * 3 / 1_000_000
            est_output = completion_tokens * 15 / 1_000_000
            est_search = 5 / 1000  # $5 per 1K requests
            est_total = est_input + est_output + est_search
            print(f"\n  💰 ESTIMATED COST (sonar-pro pricing):")
            print(f"     Input:     ~${est_input:.4f}  ({prompt_tokens} tokens × $3/1M)")
            print(f"     Output:    ~${est_output:.4f}  ({completion_tokens} tokens × $15/1M)")
            print(f"     Search:    ~${est_search:.4f}")
            print(f"     Total:     ~${est_total:.4f}")
            estimated_all = est_total * 38
            print(f"\n  📐 ESTIMATED COST FOR ALL 38 PROMPTS: ~${estimated_all:.2f}")

    # ── Save output ────────────────────────────────────────────────
    output_path = PROJECT_ROOT / prompt_config["output_path"]
    output_path.parent.mkdir(parents=True, exist_ok=True)
    formatted = format_output(text, citations, prompt_config)
    output_path.write_text(formatted, encoding="utf-8")

    print(f"\n  ✅ Output saved to: {prompt_config['output_path']}")
    print("=" * 70)

    # Show first 500 chars of response
    print("\n📝 RESPONSE PREVIEW (first 500 chars):")
    print("─" * 70)
    print(text[:500])
    if len(text) > 500:
        print(f"\n... ({len(text) - 500:,} more chars)")


if __name__ == "__main__":
    main()
